name: CI/CD for Spring Boot Project with Gradle and Firebase

on:
  push:
    branches:
      - master  # hoặc nhánh chính của bạn
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.10.2'

      - name: Build with Gradle
        run: gradle build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Firebase CLI
        uses: w9jds/firebase-action@v1
        with:
          args: login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
